Repository loot/oblivion, pull requests merged in 2021-03, with the labels that each got.

#247 Cleaning data updates
  masterlist.yaml
Labels: refactoring

#248 Refactor some message aliases
  masterlist.yaml
Labels: refactoring

#252 Replace &requiresOBSE
  masterlist.yaml
Labels: refactoring

#253 Add Simplified Chinese &quickClean translation
  masterlist.yaml
Labels: localization

#254 Replace &useIniTweakOrBashedPatch with &useINITweakInstead
  masterlist.yaml
Labels: correction, refactoring

#258 Update NVAC global message
  masterlist.yaml
Labels: refactoring

#261 Add Bulgarian localization
  masterlist.yaml
Labels: localization

#263 Update Bulgarian localization
  masterlist.yaml
Labels: localization

#264 Update Korean localization
  masterlist.yaml
Labels: localization

#265 Update aliased messages
  masterlist.yaml
Labels: correction

#266 Update OBSE Plugin Requirements message
  masterlist.yaml
Labels: correction

#267 Update Korean localization
  masterlist.yaml
Labels: localization

#268 Refactor some messages
  masterlist.yaml
Labels: refactoring

#269 Update &requiresResources
  masterlist.yaml
Labels: localization

#270 Update &requiresResources
  masterlist.yaml
Labels: localization

#279 Correct and expand Oblivion.esm swapping support
  masterlist.yaml
Labels: correction, refactoring

#287 Replace resource requirement messages
  masterlist.yaml
Labels: refactoring

#285 Update &moddingPlugin
  masterlist.yaml
Labels: localization

#291 Update &moddingPlugin
  masterlist.yaml
Labels: localization

#292 Add Italian localization
  masterlist.yaml
Labels: localization

#294 Correct Portuguese locale codes
  masterlist.yaml
Labels: correction

#295 Add missing Italian translations
  masterlist.yaml
Labels: localization
